config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'homes/top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/sign_up/confirm',  to: 'users/registrations#confirm'
    get  'users/sign_up/complete', to: 'users/registrations#complete'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    collection do
      post :confirm
    end
  end
  resources :clients do
    collection do
      get  :complete
      post :confirm
    end
  end
  resources :ufo_catchers do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates  :cilent_name,  presence: true
  validates  :phone_num,    presence: true,
                            length: { maximum: 20 },
                            numericality: { only_integer: true }
  validates  :client_email, presence: true,
                            length: { maximum: 256 }, format: { with: VALID_EMAIL_REGEX, message: "は英文字 + @~ の形式で入力してください" }
  def phone_num=(value)
    value.tr!('０-９', '0-9') if value.is_a?(String)
    super(value)
  end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many   :ufo_catcher,      through: :product_ufo
  validates  :order_date,       presence: true
  validates  :product_name,     presence: true
  validates  :product_price,    presence: true
  validates  :product_quantity, presence: true
  validates  :product_type,     presence: true
  validates  :user_id,          presence: true
end

app/models/product_client.rb
class ProductClient < ApplicationRecord
end

app/models/product_ufo.rb
class ProductUfo < ApplicationRecord
  belongs_to :product
  belongs_to :ufo_catcher
end

app/models/ufo_catcher.rb
class UfoCatcher < ApplicationRecord
  has_many   :product,      through: :product_ufo
  validates  :machine_id,       presence: true
  validates  :machine_name,     presence: true
  validates  :credit_num,       presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :email, length: { maximum: 256 }
  has_many  :product
  has_many  :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    # @clients = Client.all
    @user = current_user
    @clients = Client.where(user_id: @user.id)
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if params[:back] || !@client.save
      render :new and return
      redirect_to root_path
    elsif @client.save
      flash[:notice] = "新規取引先企業を登録しました"
      redirect_to complete_clients_path
    end
  end

  def confirm
    @client = Client.new(client_params)
    if @client.invalid?
      render :new
      return
    end
  end

  def edit
    @client = Client.find(params[:id])
  end
  
  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      flash[:notice] = "取引先企業の情報を更新しました"
      redirect_to complete_clients_path
    else
      render 'clients/edit'
    end
  end

  private

  def client_params
    params.require(:client).permit(:cilent_name, :phone_num, :client_email, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    # if @product.save
    #   flash[:notice] = "商品を新規登録しました"
    #   redirect_to products_path
    # elsif params[:back]
    #   render :new
    # else
    #   render :index
    # end
    if params[:back] || !@product.save
      render :new and return
      redirect_to root_path
    end
  end

  def confirm
    @product = Product.new(product_params)
    if @product.invalid?
      flash.now[:notice] = "入力内容にエラーがあります"
      render :new
      return
    end
  end

  private

  def product_params
    params.require(:product).permit(:order_date, :product_name, :product_price, :product_quantity, :product_type, :user_id)
  end
end

app/controllers/ufo_catchers_controller.rb
class UfoCatchersController < ApplicationController
  def index
    @ufo_catchers = UfoCatcher.all
  end

  def new
    @ufo_catchers = UfoCatcher.new
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/ufo_catchers_helper.rb
module UfoCatchersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <meta name="turbolinks-visit-control" content="reload"> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon_Zaifo.ico') %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/633f1a49a1.js" crossorigin="anonymous"></script>
  </body>

</html>

app/views/shared/_error_message.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<div class="wrapper">
  <footer class="footer">
    <p>©︎ 2023 YACHI.INC</p>
  </footer>
</div>

app/views/shared/_header.html.erb
<!-- HEADER -->
<header>
  <div class="header">
    <!-- TOPBAR -->
    <div class="top_row">
      <% if !logged_in? %>
        <div class="top_right">
          <%= link_to 'ログイン', new_user_session_path, class: 'log_in_btn' %>
          <%= link_to '新規登録', new_user_registration_path, class: 'sign_up_btn' %>
        </div>
      <% else %>
        <nav class="navbar navbar-expand-lg">
          <div class="container-fluid">
            <%= link_to 'ZaiFO', homes_top_path, class: 'navbar-brand' %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item items">
                  <%= link_to 'ホーム', homes_top_path, class: 'nav-link active' %>
                </li>
                <li class="nav-item items">
                  <%= link_to '在庫管理', products_path, class: 'nav-link' %>
                </li>
                <li class="nav-item items">
                  <%= link_to '売上一覧', homes_top_path, class: 'nav-link' %>
                </li>
                <li class="nav-item items">
                  <%= link_to '発注', homes_top_path, class: 'nav-link' %>
                </li>
                <li class="nav-item items">
                  <%= link_to '取引先一覧', clients_path, class: 'nav-link' %>
                </li>
                <li class="nav-item items">
                  <%= link_to '筐体一覧', ufo_catchers_path, class: 'nav-link' %>
                </li>
                <li class="nav-item items">
                  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </li>
              </ul>
              <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">検索</button>
              </form>
                <div class="header_user_box">
                  <div class="top_name"><%= current_user.name %></div>
                  <div class="header_name_details">
                    <%= current_user.email %>
                  </div>
                </div>
            </div>
          </div>
        </nav>
      <% end %>
    </div>
  </div>
</header>