config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'homes/top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/sign_up/confirm',  to: 'users/registrations#confirm'
    get  'users/sign_up/complete', to: 'users/registrations#complete'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    collection do
      post :confirm
    end
  end
  resources :clients do
    collection do
      get  :complete
      post :confirm
    end
  end
  resources :ufo_catchers do
    collection do
      post :confirm
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates  :cilent_name,  presence: true
  validates  :phone_num,    presence: true,
                            length: { maximum: 20 },
                            numericality: { only_integer: true }
  validates  :client_email, presence: true,
                            length: { maximum: 256 }, format: { with: VALID_EMAIL_REGEX, message: "は英文字 + @~ の形式で入力してください" }
  def phone_num=(value)
    value.tr!('０-９', '0-9') if value.is_a?(String)
    super(value)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    # @clients = Client.all
    @user = current_user
    @clients = Client.where(user_id: @user.id)
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if params[:back] || !@client.save
      render :new and return
      redirect_to root_path
    elsif @client.save
      flash[:notice] = "新規取引先企業を登録しました"
      redirect_to complete_clients_path
    end
  end

  def confirm
    @client = Client.new(client_params)
    if @client.invalid?
      render :new
      return
    end
  end

  def edit
    @client = Client.find(params[:id])
  end
  
  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      flash[:notice] = "取引先企業の情報を更新しました"
      redirect_to complete_clients_path
    else
      render 'clients/edit'
    end
  end

  private

  def client_params
    params.require(:client).permit(:cilent_name, :phone_num, :client_email, :user_id)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/complete.html.erb
<section class="user_container">
  <div class="client_complete">
    <h2 class="notice"><%= flash[:notice] %></h2>
    <input type="button" onclick="window.close();" value="ウィンドウを閉じる">
  </div>
</section>

app/views/clients/confirm.html.erb
<section class="client_container">
  <div><h2>取引先登録確認画面</h2></div>
  <%= form_with model: @client, url: clients_path do |f| %>
    <div class="client_new_field">
      <%= f.label :cilent_name, '企業名' %>
      <%= f.text_field :cilent_name, value: @client.cilent_name, readonly: true %>
    </div>
    <div class="client_new_field">
      <%= f.label :phone_num, '電話番号' %>
      <%= f.text_field :phone_num, value: @client.phone_num.tr("０-９", "0-9"), readonly: true %>
    </div>
    <div class="client_new_field">
      <%= f.label :client_email, 'メールアドレス' %>
      <%= f.text_field :client_email, value: @client.client_email.downcase, readonly: true %>
    </div>
    <div>
      <%= f.hidden_field :user_id, value: @client.user_id %>
    </div>
    <div>
      <%= f.submit '修正する', name: :back %>
      <%= f.submit '登録する', class: 'submit_btn' %>
    </div>
  <% end %>
</section>

app/views/clients/edit.html.erb
<section class="client_container">
  <div><h2>取引先編集画面</h2></div>
  <%= form_with model: @client, local: true do |f| %>
    <p><%= render "shared/error_message", obj:@client %> </p>
    <div class="client_new_field">
      <%= f.label :cilent_name, '企業名' %>
      <%= f.text_field :cilent_name %>
    </div>
    <div class="client_new_field">
      <%= f.label :phone_num, '電話番号' %>
      <%= f.text_field :phone_num %>
    </div>
    <div class="client_new_field">
      <%= f.label :client_email, 'メールアドレス' %>
      <%= f.text_field :client_email %>
    </div>
    <div>
      <%= f.hidden_field :user_id %>
    </div>
    <div class="actions">
      <%= f.submit '修正する' %>
    </div>
  <% end %>
</section>

app/views/clients/index.html.erb
<section class="client_container">
    <% if flash[:notice] %>
    <h2 class="notice"><%= flash[:notice] %></h2>
  <% end %>
  <div class="client_box">
    <h1>取引先一覧</h1>
  </div>
  <div>
    <table>
      <tbody class="client_table">
        <tr>
          <th>企業名</th>
          <th>電話番号</th>
          <th>メールアドレス</th>
        </tr>
        <% @clients.each do |client| %>
          <tr>
            <td><%= client.cilent_name %></td>
            <td><%= client.phone_num %></td>
            <td><%= client.client_email %></td>
            <td><%= link_to '編集', [:edit, client], :onclick=>"window.open(this.href,'hoge', 'height=400, width=800');return false;", rel: "noopener noreferrer" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
      <%= link_to new_client_path, 
:onclick=>"window.open(this.href,'hoge', 'height=400, width=800');return false;", rel: "noopener noreferrer" do %>
    <button class="client_registration">
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
          <path fill="none" d="M0 0h24v24H0z"></path>
          <path fill="currentColor" d="M11 11V5h2v6h6v2h-6v6h-2v-6H5v-2z"></path>
        </svg>
        取引先新規登録
      </span>
    </button>
  <% end %>
</section>

app/views/clients/new.html.erb
<section class="client_container">
  <div><h2>取引先登録画面</h2></div>
  <%= form_with model: @client, url: confirm_clients_path(@client), local: true do |f| %>
    <p><%= render "shared/error_message", obj:@client %> </p>
    <div class="client_new_field">
      <%= f.label :cilent_name, '企業名' %>
      <%= f.text_field :cilent_name, autofocus: :true, autocomplete: 'cilent_name' %>
    </div>
    <div class="client_new_field">
      <%= f.label :phone_num, '電話番号' %>
      <%= f.text_field :phone_num, autofocus: :true, autocomplete: 'phone_num', placeholder: '半角英数字のみ' %>
    </div>
    <div class="client_new_field">
      <%= f.label :client_email, 'メールアドレス' %>
      <%= f.text_field :client_email, autofocus: :true, autocomplete: 'client_email' %>
    </div>
    <div>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
    <div class="actions">
      <%= f.submit '確認画面へ' %>
    </div>
  <% end %>
</section>