config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'homes/top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post 'users/sign_up/confirm',  to: 'users/registrations#confirm'
    get  'users/sign_up/complete', to: 'users/registrations#complete'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    collection do
      post :confirm
    end
  end
  resources :clients do
    collection do
      get  :complete
      post :confirm
    end
  end
  resources :ufo_catchers do
    collection do
      post :confirm
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many   :ufo_catcher,      through: :product_ufo
  validates  :order_date,       presence: true
  validates  :product_name,     presence: true
  validates  :product_price,    presence: true
  validates  :product_quantity, presence: true
  validates  :product_type,     presence: true
  validates  :user_id,          presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    # if @product.save
    #   flash[:notice] = "商品を新規登録しました"
    #   redirect_to products_path
    # elsif params[:back]
    #   render :new
    # else
    #   render :index
    # end
    if params[:back] || !@product.save
      render :new and return
      redirect_to root_path
    end
  end

  def confirm
    @product = Product.new(product_params)
    if @product.invalid?
      flash.now[:notice] = "入力内容にエラーがあります"
      render :new
      return
    end
  end

  private

  def product_params
    params.require(:product).permit(:order_date, :product_name, :product_price, :product_quantity, :product_type, :user_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/confirm.html.erb
<section class="product_container">
  <div><h2>商品登録確認画面</h2></div>
  <%= form_with model: @product, url: products_path do |f| %>
    <div class="product_new_field">
      <%= f.label :order_date, '発注日' %>
      <%= f.text_field :order_date, value: @product.order_date, readonly: true %>
    </div>
    <div class="product_new_field">
      <%= f.label :product_name, '商品名' %>
      <%= f.text_field :product_name, value: @product.product_name, readonly: true %>
    </div>
    <div class="product_new_field">
      <%= f.label :product_price, '金額' %>
      <%= f.text_field :product_price, value: @product.product_price, readonly: true %>
    </div>
    <div class="product_new_field">
      <%= f.label :product_quantity, '数量' %>
      <%= f.text_field :product_quantity, value: @product.product_quantity, readonly: true %>
    </div>
    <div class="product_new_field">
      <%= f.label :product_type, '種類' %>
      <%= f.select :product_type, { ぬいぐるみ: 1, 雑貨: 2, その他一般系: 3, フィギュア: 4, その他コア系: 5, 食品: 6, その他: 7}, {disabled: @product.product_type}, value: @product.product_type %>
    </div>
    <div>
      <%= f.hidden_field :user_id, value: @product.user_id %>
    </div>
    <div>
      <%= f.submit '修正する', name: :back %><br />
      <%= f.submit '登録する' %>
    </div>
  <% end %>
</section>

app/views/products/index.html.erb
<section class="product_container">
  <% if flash[:notice] %>
    <h2 class="notice"><%= flash[:notice] %></h2>
  <% end %>
  <div class="product_box">
    <h1>商品一覧</h1>
  </div>
  <div>
    <table>
      <tbody class="product_table">
        <tr>
          <th>商品名</th>
          <th>種類</th>
          <th>発注日</th>
          <th>金額</th>
          <th>数量</th>
        </tr>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.product_name %></td>
            <td><%= product.product_type %></td>
            <td><%= product.order_date %></td>
            <td><%= product.product_price %></td>
            <td><%= product.product_quantity %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to new_product_path do %>
    <button class="product_registration">
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
          <path fill="none" d="M0 0h24v24H0z"></path>
          <path fill="currentColor" d="M11 11V5h2v6h6v2h-6v6h-2v-6H5v-2z"></path>
        </svg>
        商品新規登録
      </span>
    </button>
  <% end %>
</section>

app/views/products/new.html.erb
<section class="product_container">
  <div><h2>商品登録画面</h2></div>
  <%= form_with model: @product, url: confirm_products_path(@product), local: true do |f| %>
    <p><%= render "shared/error_message", obj:@product %> </p>
    <div class="product_new_field">
      <%= f.label :order_date, '発注日' %>
      <%= f.date_field :order_date, autofocus: :true, autocomplete: 'order_date' %>
    </div>
    <div class="product_new_field">
      <%= f.label :product_name, '商品名' %>
      <%= f.text_field :product_name, autofocus: :true, autocomplete: 'product_name', placeholder: '正式名称（空白は半角）' %>
    </div>
    <div class="product_new_field">
      <%= f.label :product_price, '金額' %>
      <%= f.text_field :product_price, autofocus: :true, autocomplete: 'product_price', placeholder: '半角英数字' %>
    </div>
    <div class="product_new_field">
      <%= f.label :product_quantity, '数量' %>
      <%= f.text_field :product_quantity, autofocus: :true, autocomplete: 'product_quantity', placeholder: '半角英数字' %>
    </div>
    <div class="product_new_field">
      <%= f.label :product_type, '種類' %>
      <%= f.select :product_type, { ぬいぐるみ: 1, 雑貨: 2, その他一般系: 3, フィギュア: 4, その他コア系: 5, 食品: 6, その他: 7}, {include_blank: true} %>
    </div>
    <div>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
    <div class="actions">
      <%= f.submit '確認画面へ' %>
    </div>
  <% end %>
</section>